os:
  - linux
  - osx
go:
  - "1.10.3"
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - BUILD_TYPE=package
go_import_path: github.com/algorand/node_exporter
language: go
sudo: required
matrix:
  include:
    - name: "OSX integration test"
      os: osx
      env: BUILD_TYPE=test
    - name: "Linux integration test"
      os: linux
      env: BUILD_TYPE=test
script:
  - make $BUILD_TYPE
after_success:
  - mkdir -p ./artifacts
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then cp *.tar.gz ./artifacts ; fi
addons:
  artifacts:
    s3_region: "us-east-1"
  debug: true

