os:
  - linux
  - osx
go:
  - "1.10.3"
env: BUILD_TYPE=package
go_import_path: github.com/algorand/node_exporter
language: go
sudo: required
matrix:
  include:
    - name: "OSX integration test"
      os: osx
      env: BUILD_TYPE=test
    - name: "Linux integration test"
      os: linux
      env: BUILD_TYPE=test
script:
  - make $BUILD_TYPE
