os:
  - linux
  - osx
go:
  - "1.10.3"
env: BUILD_TYPE=package
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli
go_import_path: github.com/algorand/node_exporter
language: go
sudo: required
matrix:
  include:
    - name: "OSX integration test"
      os: osx
      env: BUILD_TYPE=test
    - name: "Linux integration test"
      os: linux
      env: BUILD_TYPE=test
script:
  - make $BUILD_TYPE
after_success:
  - mkdir -p ./s3
  - cp *.tar.gz ./s3/
  #- aws s3 sync ./*.gz.tar s3://..
