os:
  - linux
  - osx
go:
  - "1.10.3"
go_import_path: github.com/algorand/node_exporter
language: go
sudo: required
matrix:
  include:
    - name: "OSX Integration tests"
      os: osx
      env:
        - BUILD_TYPE: "package"
    - name: "Linux Integration tests"
      os: linux
      env:
        - BUILD_TYPE: "package""
script:
  - make $(BUILD_TYPE)
